version: '2.6'
services:
    client:
        image: udemy-client
        build: ./client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        networks:
            - udemynetwork
    
    server:
        image: udemy-server
        build: ./server
        ports:
            - "9000:9000"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - udemynetwork
    
    monbodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod
        networks:
            - udemynetwork

networks:
    udemynetwork:
        driver: bridge